### PR TITLE
Update to IANA 2016f Timezone Release

### PR DESCRIPTION
**Pull request by jacobwgillespie**
2016f was just released, this updates the data to that version.

Replaces #359

### CODE REVIEW

**Comment by maxvipon** [comment]
Need to merge!

**Comment by SanchesS** [comment]
Need to merge this MR ASAP - today Asia/Novosibirsk timezone moved to GMT+7 timezone from GMT+6 and many applications that uses moment-timezone library started displaying wrong time

**Comment by onzag** [comment]
Merge D:

**Comment by jacobwgillespie** [comment]
@maggiepint / @mj1856 - anything I need to do to get this ready?

**Comment by maggiepint** [comment]
I've never released moment-timezone before, but I'm going to see what I can do to figure it out.

**Comment by mj1856** [comment]
I'll jump on this today.  Thanks.

**Comment by mj1856** [comment]
Complete and published `0.5.5-2016f` to GitHub and momentjs.com, but I'll need @timrwood or @ichernev to publish to npm please.

**Comment by mj1856** [comment]
Published to npm

**Pull request merged**
