### PR TITLE
Update to IANA 2016g Timezone Release

### PR DESCRIPTION
**Pull request by jacobwgillespie**
2016g was just released, this updates the data to that version.

**Note:** in the timezone data file for latest located at ftp://ftp.iana.org/tz/tzdata-latest.tar.gz, the makefile incorrectly says "VERSION= unknown" so simply running `grunt data` is currently broken since it cannot autodetect the release version.  I ran `grunt data:2016g` and then manually copied the data files to `latest.json` to create this PR.

### CODE REVIEW

**Comment by jacobwgillespie** [comment]
Looks like there are some affected tests - I may get to those in the next day or two, or otherwise owner collaboration has been enabled, so feel free to edit this PR.

**Comment by maggiepint** [comment]
Either @mj1856 or I will get this one tonight. Thanks.

**Comment by mj1856** [comment]
Sorry for the delay, I'll get on this soon.

I know the version issue is probably related to [the discussions on the tz list](http://mm.icann.org/pipermail/tz/2016-September/024198.html).

**Comment by mj1856** [comment]
I fixed the version number issue with #392.  However, I'm having some difficulties with rebuilding the data.  Maybe you could give it a try again?  If it passes for you, please rebase over this commit.

Out of curiosity, are you using Linux or a Mac?

**Comment by mj1856** [comment]
Ok, we got a good build in #394.  Thanks for your help.

**Pull request closed without merging**
