### PR TITLE
time zone data: 2015c

### PR DESCRIPTION
**Pull request by mj1856**
tzdb 2015, release April 14, 2015
http://mm.icann.org/pipermail/tz-announce/2015-April/000030.html

### CODE REVIEW

**Comment by mj1856** [comment]
@timrwood - I built this by following
https://github.com/mj1856/moment-timezone/blob/master/contributing.md#compiling-data

The data looks good, but I'm not sure why it modified so many tests.  Any ideas?

**Comment by mj1856** [comment]
Actually, it looks like it pulled in quite a lot of data changes.  Were the previous files truncating history from some point?

**Comment by mj1856** [comment]
@ichernev @icambron @timrwood 
Please help. we need to stay on top of tzdb updates, both here and on the momentjs.com/timezone website.

Is this one ok to merge? or did I screw it up somehow?

I need to now do it all over again for [2015d](http://mm.icann.org/pipermail/tz-announce/2015-April/000031.html).

**Comment by icambron** [comment]
I actually have only passing familiarity with the whole TZ project, some I'm definitely not the guy to help you here.

**Comment by mj1856** [comment]
@icambron - Sure.   I'll wait for @timrwood then.  I'm tempted to just merge it...

**Comment by timrwood** [comment]
Not sure why there are so many changes, I'm guessing it is a newline thing between windows and unix?

I opened another pr at #214 with the changes from 2015c and 2015d and the changes look to be substantially smaller.

**Pull request closed without merging**
