### PR TITLE
make compatable with moment 2.19 (as a module)

### LINKED ISSUE #540: the published version is incompatible w/ moment 2.19.0's module format
When importing as an ES module, the umd wrapper fails to account for the possible 'default' export name of moment.js (2.19 added the 'module' property to the package.json, and webpack follows it instead of main.)

### PR DESCRIPTION
**Pull request by jsg2021**
Fixes #540

### CODE REVIEW

**Comment by Sieabah** [comment]
Hope this gets in soon, none of the solutions I've found in the relevant issues actually seem to fix moment-timezone.

**Comment by brendonco** [comment]
@Sieabah You can try to downgrade moment for now.
https://github.com/moment/moment-timezone/issues/449

**Comment by Sieabah** [comment]
@brendonco I've tried downgrading the versions to 2.18.1 and that didn't work for some reason. Is there a specific version of moment-timezone I need to downgrade as well or is latest alright?

My specific code is

    import * as momentTZ from 'moment-timezone';
    ...
    momentTZ().tz....

**Comment by jmenglis** [comment]
@Sieabah 

You should be able to keep moment-timezone as latest.

I added `"moment": "2.18.1",` to my dependencies in my package.json and ran npm install

**Comment by jsg2021** [comment]
remove the “* as “ part of your import.

**Comment by Sieabah** [comment]
They're functionally equivalent.

**Comment by jsg2021** [comment]
@Sieabah no, they are not. That is a namespace import, not a default import... some libraries this works on, but not this one. This library exports a single function and replaces the `module.exports` with that function. Its subtle, but it matters.

The result of `import * as foo` results in an `Object` with all the named exports as properties. ie:
```js
exports = require(module);
foo = {}; 
for (let key in exports) {
    foo[key] = exports[key];
}
```
This is an overly simple representation, but it should make my point. 

In general for commonjs modules, if they want you to use it like so:
```js
var momentTZ = require('momentTZ')
``` 
you should use this form when translating to ES6/2015+: 
```js
import momentTZ from 'moment-timezone'
```

**Comment by brendonco** [comment]
@Sieabah Have you delete your node_modules folder, npm cache clean --force ? And npm install, once installed. Check your node_modules/moment-timezone/moment or if you're doing what @jmenglis suggested you'll be checking node_modules/moment folder instead. And check the version changelog.md if its 2.18.1. And Node version should be 7++, npm version 5++ in order your npm install to work ;)

**Comment by Sieabah** [comment]
I've done everything recommended and still have this issue. I assume moment-timezone is pulling in moment itself rather than using a peer dependency.

**Comment by jsg2021** [comment]
until this is merged, it will fail for moment@2.19.0+ in es module environments, you will need to specify `"moment":"~2.18.1"` in your app's package.json.

**Comment by Sieabah** [comment]
@jsg2021 Then there is an issue with @types/moment-timezone because doing

`import moment from 'moment-timezone'

Results in an error, which until docker bluescreened me, is something around `moment-timezone does not have a default export`, although it compiles anyway but with that error.

**Comment by jsg2021** [comment]
That is a problem with how whomever authored `@types/moment-timezone`... not this.

**Comment by Sieabah** [comment]
I suspected as much... Ah, whatever.

**Comment by stantoncbradley** [comment]
this branch works for us on react-native 0.49 and moment 2.19.  would love to see this merged so we can upgrade! 😁

**Comment by mj1856** [comment]
Please re-validate with 2.19.1.  Since 2.19.0 had a bug, and that was fixed, I'm not sure that this change is needed now.

**Comment by jsg2021** [comment]
@mj1856 moment offers an es module export. (`module` and `esnext:main` point to an es module) Which means that this library still needs this interop. (that is until this project is rewritten as an es module and compiled to commonjs for those who do not wish to use esm)

**Comment by stantoncbradley** [comment]
`2.19.1` seems compatible with `0.5.13`

"react": "16.0.0-beta.5",
"react-native": "0.49.3",

**Comment by jsg2021** [comment]
i don’t think react-native’s bundler honors `esnext:main` so, in that environment you get the commonjs build... which skirts the issue.

**Comment by mj1856** [comment]
So, unless I'm misunderstanding, this isn't absolutely required.  Given that we do want to repackage/rewrite moment-timezone into ES6 modules before a 1.0 release, I'm going to skip this for now.

Do let me know if there's some scenario I'm not considering.  Thanks.

**Comment by jsg2021** [comment]
Just clarifying... it does work now... however:

rollup and webpack (with [mainFields](https://webpack.js.org/configuration/resolve/#resolve-mainfields) set to look at `esnext:main` along with `module`, and `main`) will still hit this issue. If moment.js adds the `module` field back we will hit this problem.

**Pull request closed without merging**
