### PR TITLE
Adding country functionality from metadata

### PR DESCRIPTION
**Pull request by adgrace**
**PR for adding country functionality from metadata.**

API:
`var zones = moment.tz.zonesForCountry('US'); // returns ['America/Chicago', ' America/New_York', etc...]`
`var country = moment.tz.zone('America/Los_Angeles').country; //  returns ['US']`

Countries has been added to each zone containing the countries within the zone  as well as a countries section containing the abbreviation and zones inside to both the packed and unpacked data.

I welcome any feedback and feel free to ask any questions or for further development.

Sorry for the delay adding the feature, I am a student at university and have a high workload at the moment.

Issues requesting the feature:

- https://github.com/moment/moment-timezone/issues/289
- https://github.com/moment/moment-timezone/issues/400

Original Pull Request: https://github.com/moment/moment-timezone/pull/377 ** had some difficulty with not being able to merge and so created new pull request, sorry for any inconvenience.

### CODE REVIEW

**Comment by maggiepint** [comment]
Something is wrong here. Moment should not be in the source.

**Comment by alexgrace95** [comment]
I'm not sure how that happened! Do I need to run "grunt clean"?

**Comment by mj1856** [comment]
You've committed way more files than are actually part of the project. Did you maybe modify or delete your `.gitignore` file?

**Comment by marwahaha** [comment]
I can jump onto this @alexgrace95 if you're busy right now. It should be a quick fix, or we can chat online about how to fix this.

**Comment by mj1856** [comment]
@alexgrace95 - ping

**Comment by alexgrace95** [comment]
Hi @mj1856 & @marwahaha.
Sorry about my ultra slow reply, I have been snowed under with final year university work! I emailed @marwahaha with the email address on his GitHub profile but I am not sure if it is still active as I have had no reply?
I have a little bit of time over christmas and would like to get the pull request finished! @marwahaha please let me know how you think it should be resolved? @mj1856 could this have happened if I had pulled from the Master instead of the Dev?
Thanks,
Alex

**Comment by alexgrace95** [comment]
I have removed Moment from the source (I think may have been caused by running "bower install" at some point) and resolved the conflicts.
Thank you @marwahaha very much for all your help!

**Comment by mj1856** [comment]
Please rebase

**Comment by marwahaha** [comment]
Out of curiosity @mj1856 , what's wrong with a squash and merge? Just trying to understand.

**Comment by alexgrace95** [comment]
I have squashed and rebased and resolved the conflicts! :)

**Comment by alexgrace95** [comment]
Hi @mj1856 & @maggiepint,
Is this ready to be merged?

**Comment by reimertz** [comment]
@alexgrace95 thank you soo much for doing this! I have been looking for this dataset for about 3 days and was about to give up and just create it myself. 🙏

**Comment by maggiepint** [comment]
Can we rebase the built files out of this pull? If so, will merge.

**Comment by cmalard** [comment]
Hello there, @alexgrace95 do you still have availability to rebase this PR ? :-) Would be much appreciated :tada:

**Comment by alexgrace95** [comment]
Hi, yes will try to do it within the week, Happy New Year!

**Comment by xicovarisco** [comment]
Do you guys have an ETA on when this functionality will be merged?

**Comment by alexgrace95** [comment]
Hi All,
I have resolved the conflicts.
@maggiepint or @mj1856  please can you review?
Sorry for the delay, I have been really busy with other exciting projects.

**Comment by mmalomo** [comment]
I really need this functionality

**Comment by GaryTowers** [comment]
Any updates on this?

**Comment by diofeher** [comment]
Any updates on that?

**Comment by JefferyHus** [comment]
this needs to be merged asap

**Comment by grzegorztomasiak** [comment]
Seriously? This goes from 2017 and still no merge?

**Comment by nlyn** [comment]
e0c

**Comment by bleuscyther** [comment]
+1

**Comment by tance77** [comment]
@adgrace any progress on this?

**Comment by adgrace** [comment]
Hi @marwahaha, if I were to resolve the conflicts will this be merged?

**Comment by adgrace** [comment]
I have rebased this PR. Please can it be merged this time @ellenaua @mj1856 @marwahaha

**Comment by NuclearMachine** [comment]
This is stupid. A highly sought and needed feature has not been merged in 3 years.

**Comment by ganralf** [comment]
I am also looking for this feature 👍

**Comment by ellenaua** [comment]
It's going tomorrow to production. Version 0.5.28
I'll do more tests in my morning & release.

**Comment by adgrace** [comment]
@ellenaua Let me know if you need it rebased or anything. Look forward to it being merged 😊

**Comment by ellenaua** [comment]
Tadaaam 🥇 🥇 
It was too hard to resolve conflicts, I "picked" commits from your branch @adgrace but mentioned you in commit messages so that world knows the author.
https://momentjs.com/timezone/docs/#/using-timezones/getting-country-zones/

**Comment by Soullighter** [comment]
Far as i see, there is no solution to do this?
`var country = moment.tz.zone('America/Los_Angeles').country; // returns ['US']`

**Comment by lvillacin** [comment]
Same thoughts with @Soullighter can`moment.tz.zone().country` be implemented?

**Comment by Soullighter** [comment]
@Ivillacin
Check my codepen for solution
https://codepen.io/Soullighter/pen/MWKVvvP
Far as i remember it’s under ‘get_locale’ variable

**Pull request closed without merging**
