### PR TITLE
data: Add 2024a

### LINKED ISSUE #1091: Kazakhstan will switch to a single time zone, UTC+05:00, on March 1, 2024.
Hello!  
We are using the latest version 0.5.44, which was released on Dec 29, 2023. Since March 1, 2024, Kazakhstan will switch to a single time zone (Asia/Almaty + Asia/Qostanay => UTC+05:00) [Wikipedia Time in Kazakhstan](https://en.wikipedia.org/wiki/Time_in_Kazakhstan#:~:text=Kazakhstan%20will%20switch%20to%20a,%2C%20on%20March%201%2C%202024.). 

moment.tz("2024-01-01", "Asia/Almaty").format(); // => '2024-01-01T00:00:00+06:00' (✅)

moment.tz("2024-05-05", "Asia/Almaty").format(); // => 2024-05-05T00:00:00+06:00 (❌)

Do you have an update time zone database plan later? 
Thank you.

### LINKED ISSUE #1092: 2024a released
### Issue description

https://www.iana.org/time-zones
2024a (Released 2024-02-01)

### PR DESCRIPTION
**Pull request by tmkx**
close #1091
close #1092

### CODE REVIEW

**Comment by Flightfreak** [comment]
Thx @tmkx! Out of interest, is there a described procedure or automated script to incorporate IANA changes?

**Comment by gilmoreorless** [comment]
Quick note here: Contributor PRs to update the data are generally not accepted as-is. The wild variances in tooling on different machines have caused several bugs in past data updates. This isn't a judgement on the contributors, just a reflection of hidden subtle incompatibilities in underlying systems. It's hard to verify a data change we haven't built ourselves.
(Case in point, this PR contains some automated test fixes that are completely unrelated to the tzdb data, and just a quirk of it being the first build of 2024.)

Over the last few weeks I've worked on a fully automated data update system, anticipating this tzdb release. Once I've got some settings tweaked, I can fix it up over the weekend. Then for all future data updates, it's a single press of a button to build a PR.

**Comment by tmkx** [comment]
@gilmoreorless thanks for your work

**Comment by m-urukov** [comment]
@gilmoreorless  Thanks you! We are really looking forward to the release of 2024a ❤️

**Comment by Flightfreak** [comment]
@gilmoreorless understood. A containerised solution and a GitHub workflow? 
Anyway, sounds like a good step forward!

**Comment by gilmoreorless** [comment]
> A containerised solution and a GitHub workflow?

Pretty much! https://github.com/moment/moment-timezone/blob/6c31d29936a39207be6420e82e9f2bf2f231c6da/.github/workflows/build-data.yml

Managed to get it working after some false starts: https://github.com/moment/moment-timezone/pull/1095

**Comment by gilmoreorless** [comment]
Data 2024a is now available in release `0.5.45`.

**Pull request closed without merging**
