### PR TITLE
bypassing chrome intl timezone bug fix #517

### LINKED ISSUE #517: Wrong timezone for China/Schanghai
According to [wiki](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations)
The abbr. **CST** stands both for **Central Standard Time (North America)** and **China Standard Time**

If you set your timezone on your PC to Shanghai, moment determines timezone: 
`America/Chicago`

**System**
Ubuntu, FF or Chrome
`"moment": "2.18.1", "moment-timezone": "0.5.13"`

chrome-console

timezone

### PR DESCRIPTION
**Pull request by bolasblack**

### CODE REVIEW

**Comment by mj1856** [comment]
Thanks, but I don't think this much examination is required.  The reported bad results have all been three-character abbreviations, from what I have been able to ascertain.  Closing in favor of #553

**Comment by bolasblack** [comment]
Hi @mj1856 , I think you misunderstood me, I was trying to fix the issue #517 , not #423

In some region (for example `Asia/Shanghai`), when I executing `Intl.DateTimeFormat().resolvedOptions().timeZone` in chrome 61.0.3163.100, I will get `America/Chicago`, not `Asia/Shanghai`

I think check `Intl.DateTimeFormat().resolvedOptions().timeZone.length > 3` can not fix this issue.

**Comment by mj1856** [comment]
Oh, I see.  Let me take another look at this.  Thanks.

**Comment by gregclarke** [comment]
In addition to the above, in some circumstances the resolved timezone is incorrect. On arch linux firefox version 56.0.2 `Intl.DateTimeFormat().resolvedOptions().timeZone` returns `Etc/GMT-10` which is an hour out due to daylight savings (correct timezone is `Australia/Sydney`). The length check doesn't work in this case either. I've temporarily solved by using
`var tmpName = intlName.split('/')[0]; if (intlName && tmpName.length > 3)`

**Comment by iffy** [comment]
@mj1856 Can you please reopen this/reconsider this as a way to fix 517?

**Comment by morajabi** [comment]
@mj1856 I have this problem :( How can we fix it?

**Pull request closed without merging**
