### PR TITLE
Zone._index optimization: binary search for closest "until"

### PR DESCRIPTION
**Pull request by dashie**

### CODE REVIEW

**Comment by dashie** [comment]
Why locally I have no error but Travis build fails?

**Comment by mj1856** [comment]
Hi @dashie.  Sorry I was tuned out for a while.

You basically hit the same problem I just stumbled upon, in #743 after updating things for the latest IANA version.

Would you be so kind to rebase this off the current release?

Thanks.

**Comment by mj1856** [comment]
... Or rather, can you separate the code changes out so I can do a full build after merging?

Thanks.

**Comment by dashie** [comment]
I did it, but there are always issues with IANA version.
Anyway I've cleaned and rebased my history (https://github.com/dashie/moment-timezone/commit/fa5c4b69b6e42760a3dcc8f818e921759e7e604d) so it is simple for you to look into the changes

**Comment by ichernev** [comment]
Ooh, binary search, nice. I hope to merge this soon.

**Comment by dashie** [comment]
it is merged now?

**Comment by dashie** [comment]
@ichernev @mattjohnsonpint any news on this merge?

**Comment by mattjohnsonpint** [comment]
@gilmoreorless

**Comment by gilmoreorless** [comment]
Ah sorry I missed this one as I thought it was already being handled by others. I'm all for performance improvements so I'll take a look very soon. 😄

**Comment by gilmoreorless** [comment]
Sorry for the delay on this, @dashie. I'm still catching up on the backlog of cleanup tasks for this project.

I've finally found some time to look at this properly. My rudimentary performance tests suggest that for a zone with a lot of transitions (like `Europe/London`), this is 2–5 times faster, depending on which timestamp is being checked. Nicely done!

**Pull request merged**
