### PR TITLE
Resolve es6 loading issue where moment is undefined

### PR DESCRIPTION
**Pull request by brinley**
Fix for https://github.com/moment/moment-timezone/issues/449

### CODE REVIEW

**Comment by mj1856** [comment]
@maggiepint - Does this seem reasonable to you?

**Comment by butterflyhug** [comment]
I'm not sure this is a good idea -- will discuss in #449 since that seems to have more of the affected people.

**Comment by butterflyhug** [comment]
@brinley However this gets resolved, thanks for sending the PR!  This is really helpful to move the conversation forward.

**Comment by opavader** [comment]
@butterflyhug can this be merged for the time being? It seems to be breaking multiple react libraries with babel 6 & webpack 3 right now.

**Comment by manoj-capillary** [comment]
Not able to use moment-timezone because of this issue. Please look into this.

**Comment by Jamakase** [comment]
Hey, guys. Let's merge it!

**Comment by Etrimus** [comment]
I'm get same error, but I'm not use moment or moment-timezone directly, It is dependencies of other npm-package. What about merge this PR?...

**Comment by nick-keller** [comment]
Hey, let's merge this simple fix!

**Comment by oldboyxx** [comment]
Merge it.

**Comment by LukaszAmroz** [comment]
What is wrong with this PR? Why it can't be merged? This problem still exists and this PR seems to solve it.

**Comment by maggiepint** [comment]
Because every time we change anything at all with module loading, we break a million code bases, even if we fix a million other ones. We're a bit afraid to touch anything at this point.

**Comment by opavader** [comment]
@maggiepint If you look at the PR it's quite clear the above fix will only be applied only when the module has already failed to load. In other worlds, it won't break anything that not already broken.

**Comment by rogerkerse** [comment]
I tried this, but it did not resolve the issue for me :(

**Comment by damianobarbati** [comment]
Same here, any chance to get this solved anytime soon?

**Comment by sbayd** [comment]
Hey Fellas,

Any update on this?

**Comment by ARivas16** [comment]
Merge it, It is a problem since the last year :( 
I have a lot of issues in my app because of this

**Comment by capaj** [comment]
this fix is bit too hacky for my taste. Are you sure you can't solve it by letting webpack transpile all the js files, even the ones in `node_modules`? I have webpack 4 set up like that and I don't get this issue.

**Comment by bielcapanema** [comment]
Same issue here...
For now, I'm using [patch-package](https://www.npmjs.com/package/patch-package) to insert these PR editions on my `node_modules` folder.

Please merge it so I can remove my monkey patch for this lib.

**Comment by hamed-farag** [comment]
> Same issue here...
> For now, I'm using [patch-package](https://www.npmjs.com/package/patch-package) to insert these PR editions on my `node_modules` folder.
> 
> Please merge it so I can remove my monkey patch for this lib.

How you did it pleeease?

**Comment by joeyparis** [comment]
I'm also confused about why there is still such hesitation to accept this pull request. It's still an issue with babel@7 and 3 years later, and I can't think of a scenario where this change would break a codebase that wasn't already broken.

**Comment by david0178418** [comment]
Checking in again on this 3 year old PR.  It's only adding another check in the case that it would fail anyway.  It may not be pretty, but I'm having a hard time understanding the hesitation.

**Comment by joeyparis** [comment]
Hallelujah! I can finally remove patch-package!

**Pull request merged**
