### PR TITLE
moment package upgraded to the latest version.

### PR DESCRIPTION
**Pull request by MEGApixel23**

### CODE REVIEW

**Review by ranjithprabhuk — APPROVED** [review]

**Comment by milakucher** [comment]
hi there!
any ideas when this can be merged? :)

**Comment by sergei-lobanov** [comment]
any updates on this?

**Comment by senthur-kumaran** [comment]
Any update about this PR merge?

**Comment by gilmoreorless** [comment]
Just to be clear, `moment-timezone` itself doesn't have a vulnerability. Automated tools are only complaining because its dependency on `moment` is accurately stating that it will work with any version from `2.9.0` onwards (as mentioned at https://github.com/moment/moment-timezone/issues/997#issuecomment-1227159802).

New installs of `moment-timezone` using npm or yarn should include the latest version of `moment` anyway. Existing vulnerable versions can easily be upgraded using `npm audit fix` or similar tools (e.g. [`npx yarn-deduplicate`](https://github.com/moment/moment-timezone/issues/982#issuecomment-1119540905)). Therefore it isn't _critical_ to update the dependency definition in `package.json` — it's mostly just wanted to silence automated security tools.

@ichernev has stated a few times that he doesn't want to bump this dependency version (https://github.com/moment/moment-timezone/pull/991#issuecomment-1229384592, https://github.com/moment/moment-timezone/issues/997#issuecomment-1227159802, https://github.com/moment/moment-timezone/issues/979#issuecomment-1227200075). He's been part of the Moment team for a long time, so I generally defer to his judgement.

Personally though, I know just how irritating those automated security warnings can be, and they'll only continue to nag. As far as I know, the `dependencies` field in `package.json` really only affects people using package managers like npm, yarn, etc. It doesn't stop people from using a different version of `moment` if they want.

The documentation still says it can work with core Moment `>= 2.9.0`. I'm thinking we should probably just merge this, then revisit plans to move `moment` to `peerDependencies` instead.

@ichernev your thoughts?

**Comment by gilmoreorless** [comment]
After some discussions outside GitHub, I've decided to go ahead with this dependency bump, and accelerate plans to use `peerDependencies` instead. There have been several dev dependency updates since this PR was created, causing conflicts. I've manually merged this change in 8080504, leaving @MEGApixel23 as co-author.

I'll try to get a new release of `moment-timezone` out soon because I want to decouple this version bump from any data updates. February is generally quiet for tzdb data updates, but [March usually has at least one data update](https://observablehq.com/@gilmoreorless/tzdb-releases-per-month), so I'm expecting to need a separate data-based release sometime in the next month.

**Pull request closed without merging**
