### PR TITLE
Updated to IANA 2018i

### PR DESCRIPTION
**Pull request by ssskip**

### CODE REVIEW

**Comment by ssskip** [comment]
test break on node 11

**Comment by kkorus** [comment]
@ssskip Any update on this?

**Comment by kkorus** [comment]
Hi @ssskip can we complete this PR? 😉

**Comment by konclave** [comment]
Any changes this PR to be merged soon?

**Comment by ssskip** [comment]
@mj1856

**Comment by PKSpeleo** [comment]
Still waiting.... Please merge.... We need it!

**Comment by mj1856** [comment]
Thanks for contributing, but I'll publish 2018h, 2018i, and 2019a together in the next release, coming shortly.

Sorry for the delay - was dealing with a personal crisis.

**Comment by kkorus** [comment]
Hi @mj1856 , no worries. I hope everything is fine now.

**Pull request closed without merging**
