### PR TITLE
Move moment to peerDependencies

### PR DESCRIPTION
**Pull request by Kerumen**
It avoids having 2 instances of moment loaded in the project.

Fixes https://github.com/moment/moment-timezone/issues/132
Fixes https://github.com/moment/moment-timezone/issues/449

### CODE REVIEW

**Comment by ArthurMialon** [comment]
@Kerumen Thanks ! My life is way better now ! I'll use your branch 🚀

**Comment by idoNitzan** [comment]
When will this be merged?

**Comment by Kerumen** [comment]
I don't know.. cc @mj1856 @ssskip

**Comment by rpellerin** [comment]
I would love to see this merged as well!

**Pull request merged**
