### PR TITLE
Update to IANA 2016e Timezone Release

### PR DESCRIPTION
**Pull request by jacobwgillespie**
2016e was released a few hours ago, this updates the data to that version.

### CODE REVIEW

**Comment by JohnColvin** [comment]
Any update? The DST changes affecting Cairo take effect in 3 days.

**Comment by maggiepint** [comment]
I'll ping Tim on this one. Do be aware though: http://codeofmatt.com/2016/07/01/time-zone-chaos-inevitable-in-egypt/

**Comment by mj1856** [comment]
@JohnColvin - If Egypt is your primary concern, I'd stick with 2016d for now.  The Egyptian government essentially nullified the change made in 2016e.  This will be corrected in 2016f when it is released.

**Comment by jacobwgillespie** [comment]
This is replaced by #360 as `2016f` was just released.

**Comment by JohnColvin** [comment]
Thanks for the advice folks! We'll skip e and wait for f instead.

**Pull request closed without merging**
