### PR TITLE
Yet another PR adding TypeScript declarations

### PR DESCRIPTION
**Pull request by cspotcode**
TypeScript declarations for moment-timezone.  They have JSDoc comments, integrate with the typings included in `moment`, and have tests.

Fixes issues #341 and #370, replaces & improves upon PR #444.

### CODE REVIEW

**Comment by boblauer** [comment]
Any chance of this getting merged?

**Comment by bmagistro** [comment]
As an FYI, I have closed #444 as it appears the issue I was having has been resolved.

**Comment by kuanyen** [comment]
Why not merge this?

**Comment by HurSungYun** [comment]
When will this PR be merged?

**Comment by cspotcode** [comment]
I rebased against the latest master.  Declaration tests are still passing; the failures are due to failures from the master branch, not this PR.

Please let me know if there's anything I can do to help get this merged.

**Comment by Offirmo** [comment]
I copied `index.d.ts` from this PR into my app, it's working so far.

**Comment by isaac-gilmour-asknicely** [comment]
Hey guys, any update on where this is at?

**Comment by joebowbeer** [comment]
This is a potentially breaking change with respect to type-checking, because it will silently override `@types/moment-timezone` but I don't see any mention of it in the description of any of the releases. Is 0.5.31 the first release containing this?

**Pull request merged**
