### PR TITLE
2016d

### PR DESCRIPTION
**Pull request by timrwood**
The same as #333, but with a fix for generating test data that doesn't cause such a large diff.

### CODE REVIEW

**Comment by tlk** [comment]
Looks good to me! I am curious about how you added the population data - is there a tool for that?

**Comment by mj1856** [comment]
LGTM.  :shipit:

**Comment by timrwood** [comment]
@tlk, the tool is http://lmgtfy.com/?q=Kirov+population 😉

**Comment by tlk** [comment]
@timrwood lol, got it ;-)

**Pull request merged**
