### PR TITLE
Updated data to IANA TZDB 2018c

### PR DESCRIPTION
**Pull request by ssskip**
testGuess break on:

- America/Cancun - guess
- America/Fort_Nelson - guess
- America/Metlakatla - guess

### CODE REVIEW

**Comment by JohnColvin** [comment]
any word on when this will be merged? thanks!

**Comment by ssskip** [comment]
@JohnColvin   since 2018d (Released 2018-03-22),  i need update this pull request then

**Comment by ellenaua** [comment]
@ssskip do you have an idea how to fix failing tests? I see that when `ts.guess()` gets an equal score for multiple time zones, it's choosing zone which is more populated:
```
'America/Phoenix' scores = 0 0 population= 4200000
'America/Fort_Nelson' scores = 0 0 population= 3900
```
That's why instead of 'America/Fort_Nelson'  tz.guess() returns 'America/Phoenix'. And the same happens for 'America/Metlakatla' ('America/Anchorage' is more populated) and  'America/Cancun' ('America/Panama' is more populated). Should we just change test expectations?

**Comment by ellenaua** [comment]
I've done 2018d PR https://github.com/moment/moment-timezone/pull/596

**Pull request closed without merging**
