### PR TITLE
2020c

### PR DESCRIPTION
**Pull request by pithu**
Attempt to add 2020c tzdb data

- I am not sure if i did everything right, eg looks like update of `data/meta/latest.json` is missing. How is this generated ?
- `pacifinew` was removed from tzdb data.
- If there is anything i can do, to get this merged, please let me know

### CODE REVIEW

**Comment by krokofant** [comment]
2020d is out now

**Comment by gurumvg** [comment]
@pithu , when is this planned to be rolled out ?

**Comment by pithu** [comment]
@gurumvg no idea, i don't have write access and didn't get any response from the maintainers

**Comment by gurumvg** [comment]
> @gurumvg no idea, i don't have write access and didn't get any response from the maintainers

Is there a way where we can internally generate a new version ourself from the [java tzdata latest version](https://www.oracle.com/java/technologies/tzdata-versions.html) ?

**Comment by taylor1791** [comment]
For those of you following along at home, [release 0.5.32](https://github.com/moment/moment-timezone/releases/tag/0.5.32) contains 2020d.

**Comment by pithu** [comment]
???

**Pull request closed without merging**
