### PR TITLE
Convert to ES6

### PR DESCRIPTION
**Pull request by timrwood**
This addresses #298 by converting the source into smaller es6 modules.

This is not ready to merge yet. Here are the outstanding tasks.

Some of this work can probably be done in parallel. If you want to help out, edit the description or leave a comment about which task you are working on, then open a PR to the [es6](https://github.com/moment/moment-timezone/tree/es6) branch.
- [x] Convert source and tests to es6 modules. @timrwood
- [x] Convert [tests/moment-timezone/default.js](https://github.com/moment/moment-timezone/blob/develop/tests/moment-timezone/default.js) to es6.
- [x] Convert [tests/moment-timezone/manipulate.js](https://github.com/moment/moment-timezone/blob/develop/tests/moment-timezone/manipulate.js) to es6.
- [x] Convert [tests/moment-timezone/parse.js](https://github.com/moment/moment-timezone/blob/develop/tests/moment-timezone/parse.js) to es6.
- [x] Convert [tests/moment-timezone/utc.js](https://github.com/moment/moment-timezone/blob/develop/tests/moment-timezone/utc.js) to es6.
- [x] Update grunt tasks to es6. #311
- [x] Update `grunt data-tests` to generate correct tests. #318
- [x] Update `grunt data-pack` to output `src/data/packed.js` and `src/data/packed-2010-2020.js`. #318
- [x] Move `tasks/population.json` to an es6 module in `src/data/population.js`. #311
- [x] Move `data/meta/latest.json` to `src/data/meta.js`. #318
- [x] Discuss removing `data/**/20*.json` files.
- [ ] Build `src` into `build` for different environments. (es6, globals, amd, commonjs, umd).
- [ ] Point `package.json` and `bower.json` to the correct file entry points.
- [ ] Figure out how to run tests in a browser. sindresorhus/ava#24

### CODE REVIEW

**Comment by mj1856** [comment]
Looking good!  I'll have to do a more detailed review for more specific feedback, but glad to see this happening!

**Comment by zam6ak** [comment]
Any plans to offer TypeScript typings (package.json =>"typings") ?

**Comment by mj1856** [comment]
@zam6ak see #341

**Comment by testacode** [comment]
Why this has more info for Argentina country than master?

**Comment by brettz9** [comment]
@mj1856 : Hi... Any plans for a review in the near future?

**Comment by brettz9** [comment]
With Bower [deprecated as a service](https://bower.io/blog/2017/how-to-migrate-away-from-bower/), maybe the `bower.json` part of the to-dos can be dropped entirely?

**Comment by pdesjardins90** [comment]
@timrwood How is this going?

**Comment by pdesjardins90** [comment]
@mj1856 did you take over this? You need any help? I'd like this to move forward

**Comment by pdesjardins90** [comment]
@timrwood @mj1856 @ichernev @ellenaua anyone can revive this? I can help too

**Comment by mj1856** [comment]
I'm going to close this, just because of how much time has passed.  Sorry we never got it done, but sometimes life takes over.  At this point, I don't plan on making changes this drastic to moment-timezone.

The go-forward plan for moment and moment-timezone users is [Luxon](https://moment.github.io/luxon/).  It already has time zone support and is fully modularized ES6.

**Comment by pdesjardins90** [comment]
Thanks for the feedback and recommendation, will migrate to luxon then

**Pull request closed without merging**
