### PR TITLE
Updated data to IANA TZDB 2017b

### PR DESCRIPTION
**Pull request by ssskip**

### CODE REVIEW

**Comment by nithin123456** [comment]
moment.tz.names() doesn't work?

**Comment by Eight-Ball** [comment]
@mj1856 i'v a similar problem i think : moment.tz is undefined
Any idea ?

**Comment by pscanlon1** [comment]
+1

**Comment by pscanlon1** [comment]
moment.tz undefined here too

**Comment by davidungio** [comment]
Getting the same issue as well: `Uncaught TypeError: moment(...).tz is not a function`

**Comment by ssskip** [comment]
@nithin123456 


image

**Pull request merged**
